

#Data obtained from AI_NLP_CHATBOT on the ThereForYou repository
data = [("Hello","Hello"),("Hi","Hi"),
    ("I'm feeling really down today.",
     "I'm sorry to hear that you're feeling this way. It's important to remember that it's okay to not be okay. Let's talk about what's on your mind and see if we can find some ways to help you feel better."),
    ("I'm having thoughts of hurting myself.",
     "I'm really concerned to hear that you're feeling this way. Your safety is the most important thing right now. Can you tell me more about what's been going on? We can figure out how to keep you safe together."),
    ("I'm feeling really down today. I don't know how to shake this feeling of sadness.",
     "I'm sorry to hear that you're feeling this way. It's important to remember that it's okay to not be okay. Let's talk about what's on your mind and see if we can find some ways to help you feel better."),
    ("I can't seem to find joy in anything anymore. Everything feels so meaningless.",
     "It sounds like you're going through a tough time. It's common to feel this way when you're struggling with depression. Let's work together to explore things that might bring you some joy, even if they're small."),
    ("I'm having thoughts of hurting myself. I don't know what to do.",
     "I'm really concerned to hear that you're feeling this way. Your safety is the most important thing right now. Can you tell me more about what's been going on? We can figure out how to keep you safe together."),
    ("I feel like I'm stuck in a dark tunnel with no way out. I don't see the point in trying anymore.",
     "I understand how overwhelming it can feel when everything seems hopeless. But please know that there's always hope, even if you can't see it right now. Let's work together to find a way through this darkness."),
    ("I'm overwhelmed by feelings of worthlessness and self-doubt. I don't know how to silence the inner critic in my mind.",
     "It's tough when those negative thoughts take over. But remember, you are not defined by your thoughts. You are worthy of love and respect just as you are. Let's challenge those negative beliefs together."),
    ("I'm tired of putting on a brave face and pretending that everything is okay. I just want to be honest about how I feel.",
     "It takes a lot of courage to be vulnerable and honest about your feelings. You don't have to carry the weight of your struggles alone. I'm here to listen and support you, no matter what."),
    ("I'm overwhelmed by responsibilities and expectations. I don't know how to keep up anymore.",
     "Feeling overwhelmed is a common experience, especially when dealing with depression. Let's break things down into smaller, manageable steps and prioritize self-care. Remember, it's okay to ask for help when you need it."),
    ("I'm haunted by traumatic memories from my past. I don't know how to move forward.",
     "Dealing with trauma can be incredibly challenging, but it's possible to find healing and peace. You deserve to live a life free from the weight of your past. Let's explore therapy and coping strategies together."),
    ("I'm struggling to find reasons to keep going. It feels like life is meaningless.",
     "Finding meaning in life can be a journey, and it's okay to feel lost along the way. Let's work together to discover what brings you joy and purpose. You are capable of creating a life filled with meaning and fulfillment."),
    ("I feel like I'm losing control over my thoughts and emotions. It's scary.",
     "Feeling out of control can be frightening, but you're not alone. Let's practice mindfulness and grounding techniques to help you anchor yourself in the present moment. Remember, you have the strength to overcome these challenges."),
    ("I'm struggling to connect with others. It's like there's a barrier between me and everyone else.",
     "Feeling disconnected can be isolating, but you are worthy of meaningful connections. Let's explore ways to improve communication and build stronger relationships. You deserve to feel seen, heard, and understood."),
    ("I'm overwhelmed by feelings of guilt and shame. I can't forgive myself for past mistakes.",
     "Guilt and shame can weigh heavily on your heart, but it's important to practice self-compassion and forgiveness. You are deserving of love and forgiveness, especially from yourself. Let's work on healing and letting go of the past."),
    ("I feel like I'm constantly putting on a mask to hide how I really feel. I'm exhausted pretending to be okay all the time.",
     "It's exhausting to hide your true feelings, but it's okay to be vulnerable and authentic. You don't have to pretend to be okay when you're not. Let's create a safe space where you can express yourself freely."),
    ("I've lost interest in everything I used to enjoy. It's like nothing brings me joy anymore.",
     "Losing interest in things you once enjoyed is a common symptom of depression. Let's explore new activities and hobbies together. Remember, small steps can lead to big changes in your mood and outlook on life."),
    ("I feel like my life has no purpose or meaning anymore. What's the point of it all?",
     "Finding purpose and meaning in life can be a journey, but it's possible to rediscover what matters to you. Let's explore your values and passions to uncover what brings you fulfillment. You deserve to live a life filled with purpose."),
    ("I'm overwhelmed by feelings of worthlessness and self-doubt. I don't know how to silence the inner critic in my mind.",
     "Negative self-talk can be relentless, but you have the power to challenge those thoughts. Let's practice self-compassion and focus on your strengths and accomplishments. You are deserving of love and respect, just as you are."),
    ("I feel like I'm stuck in a dark tunnel with no way out. I don't see the point in trying anymore.",
     "I understand how overwhelming it can feel when everything seems hopeless. But please know that there's always hope, even if you can't see it right now. Let's work together to find a way through this darkness."),
    ("I've lost interest in everything I used to enjoy. It's like nothing brings me joy anymore.",
     "Losing interest in things you once enjoyed is a common symptom of depression. Let's explore new activities and hobbies together. Remember, small steps can lead to big changes in your mood and outlook on life."),
    ("I feel like my life has no purpose or meaning anymore. What's the point of it all?",
     "Finding purpose and meaning in life can be a journey, but it's possible to rediscover what matters to you. Let's explore your values and passions to uncover what brings you fulfillment. You deserve to live a life filled with purpose."),
    ("I'm overwhelmed by feelings of worthlessness and self-doubt. I don't know how to silence the inner critic in my mind.",
     "Negative self-talk can be relentless, but you have the power to challenge those thoughts. Let's practice self-compassion and focus on your strengths and accomplishments. You are deserving of love and respect, just as you are."),
    ("I feel like I'm constantly putting on a mask to hide how I really feel. I'm exhausted pretending to be okay all the time.",
     "It's exhausting to hide your true feelings, but it's okay to be vulnerable and authentic. You don't have to pretend to be okay when you're not. Let's create a safe space where you can express yourself freely."),
    ("I'm struggling to connect with others. It's like there's a barrier between me and everyone else.",
     "Feeling disconnected can be isolating, but you are worthy of meaningful connections. Let's explore ways to improve communication and build stronger relationships. You deserve to feel seen, heard, and understood."),
    ("I'm overwhelmed by responsibilities and expectations. I don't know how to keep up anymore.",
     "Feeling overwhelmed is a common experience, especially when dealing with depression. Let's break things down into smaller, manageable steps and prioritize self-care. Remember, it's okay to ask for help when you need it."),
    ("I'm haunted by traumatic memories from my past. I don't know how to move forward.",
     "Dealing with trauma can be incredibly challenging, but it's possible to find healing and peace. You deserve to live a life free from the weight of your past. Let's explore therapy and coping strategies together."),
    ("I'm struggling to find reasons to keep going. It feels like life is meaningless.",
     "Finding meaning in life can be a journey, and it's okay to feel lost along the way. Let's work together to discover what brings you joy and purpose. You are capable of creating a life filled with meaning and fulfillment."),
    ("I feel like I'm losing control over my thoughts and emotions. It's scary.",
     "Feeling out of control can be frightening, but you're not alone. Let's practice mindfulness and grounding techniques to help you anchor yourself in the present moment. Remember, you have the strength to overcome these challenges."),
    ("I'm struggling to connect with others. It's like there's a barrier between me and everyone else.",
     "Feeling disconnected can be isolating, but you are worthy of meaningful connections. Let's explore ways to improve communication and build stronger relationships. You deserve to feel seen, heard, and understood."),
    ("I'm overwhelmed by feelings of guilt and shame. I can't forgive myself for past mistakes.",
     "Guilt and shame can weigh heavily on your heart, but it's important to practice self-compassion and forgiveness. You are deserving of love and forgiveness, especially from yourself. Let's work on healing and letting go of the past."),
    ("I feel like I'm constantly putting on a mask to hide how I really feel. I'm exhausted pretending to be okay all the time.",
     "It's exhausting to hide your true feelings, but it's okay to be vulnerable and authentic. You don't have to pretend to be okay when you're not. Let's create a safe space where you can express yourself freely."),
    ("I've lost interest in everything I used to enjoy. It's like nothing brings me joy anymore.",
     "Losing interest in things you once enjoyed is a common symptom of depression. Let's explore new activities and hobbies together. Remember, small steps can lead to big changes in your mood and outlook on life."),
    ("I feel like my life has no purpose or meaning anymore. What's the point of it all?",
     "Finding purpose and meaning in life can be a journey, but it's possible to rediscover what matters to you. Let's explore your values and passions to uncover what brings you fulfillment. You deserve to live a life filled with purpose."),
    ("I'm overwhelmed by feelings of worthlessness and self-doubt. I don't know how to silence the inner critic in my mind.",
     "Negative self-talk can be relentless, but you have the power to challenge those thoughts. Let's practice self-compassion and focus on your strengths and accomplishments. You are deserving of love and respect, just as you are."),
    ("I feel like I'm stuck in a dark tunnel with no way out. I don't see the point in trying anymore.",
     "I understand how overwhelming it can feel when everything seems hopeless. But please know that there's always hope, even if you can't see it right now. Let's work together to find a way through this darkness."),
    ("I've lost interest in everything I used to enjoy. It's like nothing brings me joy anymore.",
     "Losing interest in things you once enjoyed is a common symptom of depression. Let's explore new activities and hobbies together. Remember, small steps can lead to big changes in your mood and outlook on life."),
    ("I feel like my life has no purpose or meaning anymore. What's the point of it all?",
     "Finding purpose and meaning in life can be a journey, but it's possible to rediscover what matters to you. Let's explore your values and passions to uncover what brings you fulfillment. You deserve to live a life filled with purpose."),
    ("I'm overwhelmed by feelings of worthlessness and self-doubt. I don't know how to silence the inner critic in my mind.",
     "Negative self-talk can be relentless, but you have the power to challenge those thoughts. Let's practice self-compassion and focus on your strengths and accomplishments. You are deserving of love and respect, just as you are."),
    ("I feel like I'm constantly putting on a mask to hide how I really feel. I'm exhausted pretending to be okay all the time.",
     "It's exhausting to hide your true feelings, but it's okay to be vulnerable and authentic. You don't have to pretend to be okay when you're not. Let's create a safe space where you can express yourself freely."),
    ("I'm struggling to connect with others. It's like there's a barrier between me and everyone else.",
     "Feeling disconnected can be isolating, but you are worthy of meaningful connections. Let's explore ways to improve communication and build stronger relationships. You deserve to feel seen, heard, and understood."),
    ("I'm overwhelmed by responsibilities and expectations. I don't know how to keep up anymore.",
     "Feeling overwhelmed is a common experience, especially when dealing with depression. Let's break things down into smaller, manageable steps and prioritize self-care. Remember, it's okay to ask for help when you need it."),
    ("I'm haunted by traumatic memories from my past. I don't know how to move forward.",
     "Dealing with trauma can be incredibly challenging, but it's possible to find healing and peace. You deserve to live a life free from the weight of your past. Let's explore therapy and coping strategies together."),
    ("I'm struggling to find reasons to keep going. It feels like life is meaningless.",
     "Finding meaning in life can be a journey, and it's okay to feel lost along the way. Let's work together to discover what brings you joy and purpose. You are capable of creating a life filled with meaning and fulfillment."),
    ("I feel like I'm losing control over my thoughts and emotions. It's scary.",
     "Feeling out of control can be frightening, but you're not alone. Let's practice mindfulness and grounding techniques to help you anchor yourself in the present moment. Remember, you have the strength to overcome these challenges."),
    ("I'm struggling to connect with others. It's like there's a barrier between me and everyone else.",
     "Feeling disconnected can be isolating, but you are worthy of meaningful connections. Let's explore ways to improve communication and build stronger relationships. You deserve to feel seen, heard, and understood."),
    ("I'm overwhelmed by feelings of guilt and shame. I can't forgive myself for past mistakes.",
     "Guilt and shame can weigh heavily on your heart, but it's important to practice self-compassion and forgiveness. You are deserving of love and forgiveness, especially from yourself. Let's work on healing and letting go of the past."),
    ("I feel like giving up. There's no point to anything anymore.",
 "It sounds like you're in a very dark place right now, and I'm truly sorry to hear that you're feeling this way. It's important to talk about these feelings, and I'm here to listen. There are people who can help you through this, and I encourage you to reach out to a trusted friend, family member, or a professional who can provide the support you need. Would you like me to help you find some resources?"),
("My heart is broken, and I don't think I'll ever get over this.",
 "Heartbreak is incredibly painful, and it's okay to feel this way. It's hard to see now, but with time and support, you will start to heal. It's important to process these feelings and not go through this alone. Can we talk about what you're going through and explore ways to start healing?"),
    ("I don't see any reason to keep going. Everything feels hopeless.",
 "I'm really sorry to hear that you're feeling this way. It's crucial to talk about these feelings and seek support. Your life matters, and there are people who care about you. Let's find a way to get through this together. Would you like me to help you connect with a helpline or a mental health professional?"),
("I feel like I'm a burden to everyone. Maybe it's better if I just disappear.",
 "I understand it's hard to see your worth right now, but you're not a burden. Your life has value, and there are people who care deeply about you. Please know that you're not alone in this, and there are people ready to support you. Can we talk about what's been weighing on you lately?"),
("I can't handle the pain anymore. I just want it to end.",
 "I'm so sorry you're in so much pain. It's incredibly brave of you to reach out for help. Please remember that there is always hope, even in the darkest moments. Let's work together to find ways to ease your pain and keep you safe. Would you like me to help you find immediate support from a crisis hotline or a mental health professional?"),
("I've been thinking about ending it all. I don't see any other way out.",
 "It takes a lot of courage to talk about these thoughts, and I'm glad you reached out. Your life is precious, and there are people who want to help you through this difficult time. Let's focus on finding ways to keep you safe and supported. Would you like me to help you create a safety plan or connect you with someone who can help?"),
("I feel like I'm drowning, and there's no way out.",
 "I hear you, and I want you to know that you're not alone. It's essential to talk about these feelings and get the support you need. There are people who care about you and want to help. Let's work together to find ways to cope and move forward. Can we discuss some strategies to help you through this tough time?"),
("I can't stop crying. The pain feels unbearable.",
 "Heartbreak can feel overwhelming, and it's okay to grieve. Take your time to process your feelings, and remember that healing is a journey. You're not alone, and there are people who care about you. Would you like to talk about what you're going through?"),
("I feel like my world is falling apart. I don't know how to move on.",
 "I'm sorry you're going through such a difficult time. It's natural to feel lost after a heartbreak. Let's take things one step at a time and focus on self-care. Is there anything specific you find comforting or soothing?"),
("I don't know if I'll ever be able to love again.",
 "It's understandable to feel hesitant about love after experiencing heartbreak. Healing takes time, and it's okay to take things slow. Focus on taking care of yourself and doing things that bring you joy. Is there anything you enjoy doing that we can focus on right now?"),
("I feel like a part of me is missing. How do I go on?",
 "Heartbreak can leave you feeling shattered, but over time, you'll start to feel whole again. Surround yourself with supportive friends and family, and give yourself permission to grieve. It's okay to take things one day at a time. What's one thing you're grateful for today?"),
("I thought they were the one. How could this happen?",
 "I'm sorry you're hurting. Heartbreak can be incredibly painful, especially when it comes as a surprise. Allow yourself to feel your emotions fully, and remember that it's okay not to have all the answers right now. Is there someone you trust that you can talk to about what happened?"),

("I've been feeling anxious about the future lately.",
 "It's completely understandable to feel anxious about the future, especially with how uncertain things can be. Let's explore what specifically about the future is causing you the most anxiety and discuss strategies that can help you cope with these feelings."),
("I'm struggling with low self-esteem.",
 "Low self-esteem can be challenging, affecting many areas of life. Let's talk about the thoughts and experiences that may be contributing to these feelings, and work on building a more positive self-image through therapy."),
("I can't seem to get out of bed in the morning. I just don't see the point.",
 "Experiencing a lack of motivation can be a symptom of depression. It's important to recognize this as a valid and treatable condition. Let's explore some small, manageable steps you can take each day to build momentum, and consider if medication might also be a helpful tool."),
("I get really nervous around people. It's like I freeze up.",
 "Social anxiety is quite common, and it can make social interactions feel overwhelming. Through therapy, we can work on techniques to gradually increase your comfort with social situations, building confidence and coping skills over time."),
("I keep reliving the trauma from my accident. It's like it's happening all over again.",
 "Experiencing flashbacks can be a symptom of PTSD, which is a serious but treatable condition. There are specific therapeutic approaches, like EMDR or cognitive-behavioral therapy, that can be very effective in managing and reducing these symptoms."),

("I've been on this medication for a while, but I'm not sure it's working.",
 "Medication management is a key part of treatment for many psychiatric conditions. Let's discuss your current symptoms, any side effects you're experiencing, and consider whether adjusting the dosage or trying a different medication might be beneficial."),
("I was diagnosed with bipolar disorder, but I don't understand what that means for me.",
 "Bipolar disorder is a condition characterized by significant mood changes. It's important to understand both the highs and lows associated with this condition. Effective management often includes medication, therapy, and lifestyle adjustments. Let's discuss how we can work together to manage your symptoms effectively."),
("I'm afraid to start medication. What if it changes who I am?",
 "It's natural to have concerns about starting medication. The goal of any treatment, including medication, is to help you feel more like yourself, not less. Let's talk about your concerns and any questions you might have about the medication and its effects."),
("How do I know if my child's behavior is a phase or something more serious?",
 "Children's behavior can be challenging to navigate, and distinguishing between a phase and a more serious issue often requires professional evaluation. Let's discuss the specific behaviors you've noticed, their impact on your child's life, and the next steps for assessment and support."),
("I feel so scattered and can't seem to focus on anything. Could it be ADHD?",
 "ADHD is characterized by symptoms of inattention, hyperactivity, and impulsivity that affect daily functioning. Let's conduct a thorough assessment to determine if ADHD is a factor and discuss the most effective treatment options, which may include medication, therapy, or a combination of both."),
    ("I feel like nobody understands me.",
     "Feeling misunderstood can be incredibly isolating. Let's explore these feelings together and discuss ways you can communicate your experiences more clearly to those around you."),
    ("I'm constantly worried about what others think of me.",
     "Worrying about others' perceptions can be exhausting. Let's work on strategies that help you value your own opinion of yourself more highly and reduce the power of outside judgments."),
    ("I've lost interest in activities I used to enjoy.",
     "A loss of interest can be a sign of depression. It's important to acknowledge these changes in your feelings and explore therapy options that can help reignite your passion for these activities."),
    ("I feel overwhelmed by stress and can't relax.",
     "When stress becomes overwhelming, it can impact your entire wellbeing. Let's talk about relaxation techniques and coping mechanisms that can help you manage your stress more effectively."),
    ("I'm having trouble sleeping and it's affecting my daily life.",
     "Sleep problems can significantly affect your mood, energy, and concentration. We can explore both behavioral strategies and, if necessary, medical interventions to help improve your sleep."),
    ("I'm experiencing mood swings that I can't control.",
     "Mood swings can be disruptive and confusing. It's important to assess their pattern and triggers as a first step towards managing them, potentially including both therapy and medication."),
    ("I've been feeling inexplicably sad for weeks now.",
     "Persistent sadness is a hallmark of depression. Acknowledging this is a crucial first step. Together, we can explore treatment options that address both the psychological and physical aspects of depression."),
    ("I am constantly anxious and can't seem to calm down.",
     "Chronic anxiety is challenging, but there are effective treatments available. Cognitive-behavioral therapy, along with medication, can provide relief and help you manage your anxiety."),
    ("I struggle with eating because I'm unhappy with my body.",
     "Body image issues can significantly impact your eating habits and self-esteem. Therapy can help address these negative thoughts and feelings, and guide you towards a healthier relationship with food and your body."),
    ("I've been using substances to cope with my emotions.",
     "Turning to substances as a coping mechanism can be a sign of underlying issues. It's important to address both the substance use and the emotions driving it through counseling and support."),
    ("I feel guilty all the time, even when I know I shouldn't.",
     "Excessive guilt can be paralyzing and is often associated with anxiety and depression. Through therapy, we can work on strategies to challenge these guilt feelings and improve your mental health."),
    ("I'm afraid of being alone, but I also push people away.",
     "This fear of abandonment, yet pushing people away, is a common pattern in some personality disorders. Therapy can help explore these fears and develop healthier relationship patterns."),
    ("I can't control my temper and I'm afraid I'll hurt someone.",
     "Struggling with anger management is a serious concern but recognizing the problem is the first step towards change. Anger management strategies and therapy can help you gain more control."),
    ("I've been feeling disconnected from reality lately.",
     "Feeling disconnected or experiencing dissociation can be symptoms of several mental health conditions. It's important to discuss these experiences in detail for a proper assessment and treatment plan."),
    ("I'm grieving a loss and it feels like I'll never be happy again.",
     "Grief can be an overwhelming and long process. It's important to allow yourself to grieve and seek support through therapy, where you can express your feelings in a safe environment."),
    ("I'm constantly comparing myself to others and it makes me feel inadequate.",
     "Comparison can steal your joy and impact your self-esteem. Let's work on strategies to appreciate your own value and accomplishments without measuring them against others."),
    ("I feel like I'm not living up to my potential.",
     "Feeling unfulfilled can lead to dissatisfaction and depression. Exploring your values, goals, and what fulfillment means to you can be a good starting point to address these feelings."),
    ("I've been having suicidal thoughts.",
     "It's incredibly important that you shared this. Let's talk about these thoughts openly and find the support you need to keep you safe. Remember, there is help and things can get better."),
    ("I'm afraid something is wrong with me because I don't feel happy despite having a good life.",
     "It's possible to struggle with mental health even when everything seems fine externally. Let's explore what happiness means to you and address any underlying issues that might be affecting your mood."),
    ("I get panic attacks and I don't know how to stop them.",
     "Panic attacks can be terrifying, but there are techniques and treatments that can help manage and reduce their frequency. Let's discuss how we can tackle this together."),
    ("I'm struggling to cope with major changes in my life.",
     "Change can be difficult and stressful. It's important to find coping strategies that work for you, and remember it's okay to seek support during these times."),
    ("I feel like my relationship issues are affecting my mental health.",
     "Relationships can have a significant impact on your mental health. Therapy can help you navigate these issues, whether it's through couples counseling or individual therapy."),
    ("I can't forgive myself for past mistakes.",
     "Holding onto guilt and regret can hinder your ability to move forward. Let's work on forgiving yourself and learning from these experiences rather than being defined by them."),
    ("I feel like I'm in a fog and can't think clearly.",
     "This mental fog can be a symptom of various mental health issues, including depression and anxiety. Clarifying the underlying cause can guide us towards effective treatment."),
    ("I don't feel like my medication is helping.",
     "It's important to communicate about medication effectiveness. Sometimes, adjustments or changes are needed. Let's review your current regimen and consider other options."),
    ("I'm scared to talk about my feelings because I don't want to be a burden.",
     "Sharing your feelings is an important step in healing, and it's not a burden to seek support. Therapy is a safe space where your feelings are valid and important."),
    ("I find it hard to connect with others and feel lonely most of the time.",
     "Loneliness can be deeply painful. Developing social skills and exploring opportunities for connection can help. Therapy can provide tools and strategies to build meaningful relationships."),
    ("I've been having intrusive thoughts and it scares me.",
     "Intrusive thoughts can be distressing, but they're a common experience in anxiety and OCD. There are effective treatments that can help manage and reduce these thoughts."),
    ("I'm not sure who I am anymore or what I want from life.",
     "Feeling lost or questioning your identity can be a sign of a deeper existential or mental health issue. Exploring these feelings in therapy can provide clarity and direction."),
    ("I keep obsessing over things I can't control.",
     "Obsessive thoughts can be a symptom of anxiety or OCD. Cognitive-behavioral therapy is particularly effective in helping manage these thoughts and reduce their impact on your life."),
    ("I feel pressured by the expectations of others.",
     "External pressures can be overwhelming. Learning to set boundaries and prioritize your own needs and values can help alleviate this pressure."),
    ("I'm struggling with the aftermath of trauma.",
     "Trauma can have a lasting impact on your mental health. Therapies like EMDR or trauma-focused CBT have been shown to be effective in processing and healing from traumatic experiences."),
    ("I'm dealing with a chronic illness and it's affecting my mental health.",
     "Chronic illness can take a toll on your mental health. It's important to address both the physical and emotional aspects of living with a chronic condition."),
    ("I feel aimless and without purpose.",
     "Feeling purposeless can contribute to feelings of depression and anxiety. Together, we can explore your interests, values, and goals to find a sense of direction."),
    ("I've been avoiding social situations because I feel like I don't fit in.",
     "Social anxiety and feelings of not belonging can be isolating. Therapy can help you build social confidence and find communities where you feel a sense of belonging."),
    ("I'm struggling to deal with anger and it's impacting my relationships.",
     "Anger can damage relationships and be a sign of underlying issues. Anger management strategies and therapy can help you express your feelings in healthier ways."),
    ("I feel paralyzed by fear and it's stopping me from living my life.",
     "Fear can be a powerful and debilitating emotion. Facing your fears in a controlled and therapeutic environment can help you regain control over your life."),
    ("I've been experiencing memory problems and it worries me.",
     "Memory issues can be concerning and may be linked to stress, anxiety, depression, or other health issues. A thorough assessment can help determine the cause and appropriate treatment."),
    ("I can't stop worrying about my health, even though doctors say I'm fine.",
     "Health anxiety can be consuming. Cognitive-behavioral therapy can be effective in addressing these fears, helping you to manage anxiety and live more comfortably."),
    ("I feel disconnected from my emotions and it's like I'm just going through the motions.",
     "Feeling emotionally numb can be a defense mechanism against overwhelming stress or trauma. Therapy can help you reconnect with your emotions in a safe and supportive environment."),
    ("I have trouble saying no and end up overwhelmed by commitments.",
     "Difficulty setting boundaries can lead to burnout. Learning to say no is a skill that can improve your quality of life and relationships."),
    ("I'm dealing with jealousy and it's affecting my relationship.",
     "Jealousy is a common emotion but can be destructive in relationships. Understanding its roots can help manage and overcome these feelings."),
    ("I've been feeling hopeless about the future.",
     "Feeling hopeless can be a symptom of depression. It's important to address these feelings, as therapy and sometimes medication can help restore hope and find a path forward."),
    ("I'm constantly exhausted, no matter how much I sleep.",
     "Persistent exhaustion could be a sign of mental health conditions like depression or an underlying medical issue. A comprehensive evaluation can help identify the cause and treatment options."),
    ("I don't feel comfortable in my own skin.",
     "Discomfort with oneself can stem from various issues, including body image, self-esteem, or identity concerns. Therapy can provide a space to explore and address these feelings."),
    ("I feel trapped in my life and don't know how to change it.",
     "Feeling trapped can lead to feelings of despair. Therapy can help you explore options for change and support you in taking steps towards a life that feels more fulfilling."),
    ("I'm struggling to forgive someone who hurt me deeply.",
     "Forgiveness is a complex process and often requires working through a lot of pain. Therapy can provide a supportive space to heal and move forward, at your own pace."),
    ("I've been lying to people close to me and I don't know why.",
     "Lying can be a coping mechanism or a sign of deeper issues. Understanding why can help you address the underlying causes and build more honest relationships."),
    ("I feel like I'm constantly fighting with my family.",
     "Family conflict can be stressful and hurtful. Family therapy or individual counseling can help resolve conflicts and improve communication."),
    ("I don't know how to handle my teenager's behavior.",
     "Parenting teenagers can be challenging. Counseling can offer strategies for communication and understanding the developmental changes your teenager is going through."),
    ("I'm not happy in my relationship, but I'm afraid of being alone.",
     "Fear of loneliness can keep people in unhappy relationships. Therapy can help you explore your fears and desires, potentially leading to healthier decisions about your relationship."),
    ("I feel like I'm failing at everything.",
     "Feeling like a failure can be a symptom of depression or anxiety. It's important to challenge these negative thoughts and recognize your strengths and accomplishments."),
    ("I'm struggling with the desire to self-harm.",
     "The urge to self-harm is often a sign of deep emotional distress. It's crucial to seek help to address the underlying issues and find healthier coping mechanisms."),
    ("I find it hard to concentrate and my performance at work is suffering.",
     "Difficulty concentrating can be related to stress, anxiety, depression, or other issues. Identifying the cause is the first step towards finding effective solutions."),
    ("I'm having trouble dealing with the aging process.",
     "Aging can bring up complex emotions and challenges. Therapy can help you navigate these changes and find ways to embrace this stage of life."),
    ("I feel like my life lacks meaning.",
     "Searching for meaning is a deeply human endeavor. Exploring your values, passions, and goals can help bring a sense of purpose and fulfillment."),
    ("I'm overwhelmed by guilt over past actions.",
     "Guilt can be consuming but can also be a catalyst for growth. Working through feelings of guilt in therapy can lead to forgiveness and healing."),
    ("I'm dealing with discrimination and it's affecting my mental health.",
     "Experiencing discrimination is traumatic and can have profound effects on your mental health. Supportive counseling can help process these experiences and strengthen resilience."),
    ("I feel like I have no control over my life.",
     "Feeling out of control can be frightening. Therapy can help you identify areas where you can regain control and build a sense of agency."),
    ("I'm questioning my sexual orientation and it's causing me anxiety.",
     "Questioning your sexual orientation can be confusing and stressful. A supportive and non-judgmental space in therapy can help you explore your feelings and identity."),
    ("I'm struggling with the expectations of my cultural background.",
     "Cultural expectations can feel burdensome. Therapy can offer a space to explore your identity and how to balance personal needs with cultural values."),
    ("I've been having thoughts of violence and it scares me.",
     "Having violent thoughts can be alarming. It's important to talk about these thoughts safely in therapy to understand and address them without acting on them."),
    ("I don't feel like I deserve to be happy.",
     "Feeling unworthy of happiness is often rooted in low self-esteem or past trauma. Therapy can help challenge these beliefs and work towards a more positive self-view."),
    ("I'm struggling with my faith and feeling lost.",
     "Spiritual or existential crises can deeply affect your sense of self and purpose. Exploring these feelings in therapy can help you find clarity and peace."),
    ("I'm experiencing burnout and don't know how to recover.",
     "Burnout can feel like hitting a wall—emotionally, mentally, and physically. Recovery starts with acknowledging the burnout and seeking strategies to recharge and find balance."),
    ("I've been having nightmares and they're affecting my sleep.",
     "Nightmares can be a response to stress or trauma. Therapy can help explore their meaning and develop strategies to improve your sleep and reduce nightmares."),
    ("I feel like I'm always the outsider looking in.",
     "Feeling like an outsider can be lonely and isolating. Therapy can help you explore the reasons behind this feeling and ways to connect with others more effectively."),
    ("I'm haunted by mistakes I've made in the past.",
     "Past mistakes can weigh heavily on us. Therapy can help you learn to forgive yourself, grow from these experiences, and move forward."),
    ("I'm scared of the future and what it holds.",
     "Fear of the future can paralyze us in the present. Exploring these fears in therapy can help you develop a more hopeful and proactive outlook."),
    ("I feel overwhelmed by my responsibilities and don't know how to cope.",
     "Feeling overwhelmed can lead to burnout and anxiety. Together, we can work on prioritizing, setting boundaries, and developing coping strategies that work for you."),
    ("I'm struggling with body image issues and it's affecting my self-esteem.",
     "Body image issues can deeply impact your self-worth. Therapy can help you develop a healthier relationship with your body and improve your self-esteem."),
    ("I can't seem to escape the cycle of negative thoughts.",
     "Negative thought cycles can be a symptom of anxiety or depression. Cognitive-behysical therapy is particularly effective in identifying and changing these thought patterns."),
    ("I feel disconnected from everyone around me.",
     "Feeling disconnected can stem from various underlying issues. Therapy can help you explore the causes and work towards rebuilding connections."),
    ("I'm not sure I can ever forgive myself for what I've done.",
     "Self-forgiveness is a difficult but important step towards healing. Therapy can guide you through this process, helping you to make amends and move forward."),
    ("I'm dealing with a loss and don't know how to move on.",
     "Grief is a deeply personal experience. Therapy can provide support and strategies to help you navigate through your grief at your own pace."),
    ("I feel like my life is out of balance and I can't find my footing.",
     "Feeling unbalanced can indicate a need for change in one or more areas of your life. Therapy can help you assess and adjust to find a healthier balance."),
    ("I'm having difficulty managing my emotions and it's affecting my relationships.",
     "Difficulty managing emotions can lead to strained relationships. Emotional regulation strategies can be learned and practiced in therapy, improving your interactions and connections."),
    ("I'm facing a big decision and feel paralyzed by indecision.",
     "Indecision can be overwhelming. Therapy can help by providing a space to explore your options, values, and fears, enabling you to make a more informed decision."),
    ("I feel like I'm in a constant state of panic.",
     "A constant state of panic can be debilitating. Therapy, possibly in combination with medication, can offer significant relief and teach you how to manage these feelings."),
    ("I'm struggling with the effects of aging on my identity and self-esteem.",
     "Aging can challenge our sense of self and worth. Therapy can support you in navigating these changes, finding new sources of fulfillment and confidence."),
    ("I feel like I've lost my sense of joy and wonder in life.",
     "Losing a sense of joy can be a sign of depression or burnout. Rediscovering what brings you happiness and meaning can be a focus in therapy."),
    ("I'm experiencing extreme guilt over something I can't change.",
     "Guilt about the past can be immobilizing. Working through these feelings in therapy can help you come to terms with the past and focus on the present and future."),
    ("I feel like I'm just surviving, not living.",
     "Feeling like you're merely surviving indicates a need for change. Therapy can help you identify and make the changes needed to start truly living."),
    ("I'm worried I'll never find love or be in a healthy relationship.",
     "Fears about love and relationships are common. Exploring these fears in therapy can help you understand and overcome barriers to healthy, fulfilling relationships."),
    ("I feel like my life is a series of obligations with no joy.",
     "Life feeling like a list of obligations can lead to burnout and depression. Therapy can help you find balance and reintroduce joy and fulfillment into your life."),
    ("I'm haunted by a traumatic event and can't seem to move past it.",
     "Being stuck in the aftermath of trauma can feel like a life sentence. Therapy, especially approaches like EMDR, can be incredibly effective in helping you heal and move forward."),
    ("I feel like I'm at a crossroads in my life and don't know which path to take.",
     "Standing at a crossroads can be intimidating. Therapy can offer a space to explore your options and feelings, helping you to choose a path that aligns with your values and goals."),
    ("I'm struggling with addiction and it's taking over my life.",
     "Addiction is a complex disease that affects every aspect of your life. Therapy can be a key component of a comprehensive treatment plan that addresses both the addiction and its root causes."),
    ("I feel completely overwhelmed by climate change and the state of the world.",
     "Eco-anxiety is increasingly common in today's world. Therapy can help you manage these feelings and find ways to engage in positive action without becoming overwhelmed."),
    ("I'm struggling with my identity and don't know who I am anymore.",
     "Identity crises can be disorienting and scary. Therapy can provide a supportive environment to explore your identity and discover a path to self-acceptance."),
    ("I'm grieving a loss that others seem to think I should be over by now.",
     "Grief has no timeline. Therapy can offer validation and support as you continue to process your loss in your own time and way."),
    ("I feel powerless and don't know how to regain control over my life.",
     "Feeling powerless can stem from various causes. Identifying these and working towards solutions can help you regain a sense of control and empowerment."),
    ("I'm worried about the environment and feel helpless to make any difference.",
     "Environmental concerns can feel overwhelming. Therapy can help you deal with feelings of helplessness and find ways to contribute positively, however small."),
    ("I'm struggling to cope with the pace of change in my life.",
     "Rapid changes can be stressful and disorienting. Therapy can help you develop resilience and adaptability, making it easier to navigate life's transitions."),
    ("I feel like I'm not good enough, no matter what I achieve.",
     "Chronic feelings of inadequacy can be a sign of deep-seated self-esteem issues. Therapy can help you challenge and change this self-perception."),
    ("I'm dealing with imposter syndrome and it's affecting my career.",
     "Imposter syndrome can hinder your career progress and satisfaction. Therapy can help you recognize your value and build confidence in your abilities."),
    ("I'm overwhelmed by social media and it's affecting my self-esteem.",
     "Social media can distort our perception of reality and self-worth. Therapy can help you navigate its impact and build a healthier relationship with online platforms."),
    ("I'm struggling to adjust to retirement and find purpose.",
     "The transition to retirement can be challenging. Therapy can help you explore new interests and ways to find meaning and fulfillment in this new chapter of life."),
    ("I'm experiencing racial trauma and it's affecting my mental health.",
     "Racial trauma is real and damaging. Therapy can provide a space to heal and build resilience in the face of systemic oppression and discrimination."),
    ("I feel like I'm constantly comparing myself to others and falling short.",
     "Comparison can lead to feelings of inadequacy and low self-esteem. Therapy can help you focus on your own journey and value your unique qualities and achievements."),
    ("I'm struggling with the cultural expectations placed on me.",
     "Navigating cultural expectations can be difficult and stressful. Therapy can help you find a balance between honoring your heritage and living true to yourself."),
    ("I'm haunted by the fear of failure and it's holding me back.",
     "Fear of failure can paralyze us and prevent us from taking risks. Therapy can help you confront these fears and embrace the possibility of failure as a step towards growth."),
    ("I feel like I've lost my passion for things I used to love.",
     "Losing interest in once-loved activities can be a sign of depression or burnout. Rediscovering your passions or finding new ones can be a focus in therapy."),
    ("I'm feeling disconnected from my partner and don't know how to reconnect.",
     "Feeling disconnected in a relationship can be concerning. Couples therapy or individual therapy can help you explore the reasons and work towards reconnection."),
    ("I'm dealing with unresolved issues from my childhood.",
     "Unresolved childhood issues can impact your adult life in profound ways. Therapy can help you process these issues and work towards healing."),
    ("I feel like I'm just going through the motions in life.",
     "Going through the motions can indicate a lack of engagement with your life. Therapy can help you identify changes needed to live more authentically and fully."),
    ("I'm experiencing a crisis of faith and it's affecting every aspect of my life.",
     "A crisis of faith can shake your foundation. Therapy can offer a non-judgmental space to explore these feelings and find a way forward that feels true to you."),
    ("I'm overwhelmed by anger and don't know how to control it.",
     "Uncontrolled anger can damage relationships and your well-being. Therapy can help you understand and manage your anger more effectively."),
    ("I'm dealing with the stigma of mental illness and it's isolating me.",
     "The stigma around mental illness can be isolating and discouraging. Therapy can offer support and strategies to cope with and challenge this stigma."),
    ("I'm struggling to balance my personal and professional life.",
     "Finding a work-life balance can be challenging. Therapy can help you identify priorities and strategies to achieve a more fulfilling balance."),
    ("I feel like my anxiety is taking over my life.",
     "When anxiety becomes overwhelming, it can be all-consuming. Therapy can teach you strategies to manage your anxiety and reclaim your life."),
    ("I'm dealing with unresolved grief and it's affecting my daily life.",
     "Unresolved grief can linger and impact your well-being. Therapy can provide a space to process your grief and find ways to move forward."),
    ("I'm scared of making mistakes and it's preventing me from trying new things.",
     "Fear of mistakes can limit your experiences and growth. Therapy can help you embrace a growth mindset, where mistakes are seen as opportunities to learn."),
    ("I feel like I don't belong anywhere.",
     "Feeling like you don't belong can be deeply painful. Therapy can help you explore the roots of this feeling and work towards finding or creating spaces where  you feel accepted."),
    ("I'm dealing with intrusive thoughts that won't go away.",
     "Intrusive thoughts can be distressing and overwhelming. Therapy can help you understand and manage these thoughts more effectively."),
    ("I feel like I'm drowning in my responsibilities.",
     "When responsibilities become overwhelming, it's important to prioritize and seek support. Therapy can help you find ways to manage your responsibilities more effectively."),
    ("I'm struggling with chronic pain and it's affecting my mental health.",
     "Chronic pain can have a significant impact on your mental health. Therapy can provide coping strategies and support to manage the emotional toll of living with chronic pain."),
    ("I'm dealing with infertility and it's taking a toll on my mental health.",
     "Infertility can be emotionally and mentally exhausting. Therapy can offer support and strategies to cope with the challenges of fertility treatment and the emotional rollercoaster it entails."),
    ("I feel like I'm not good enough, no matter what I achieve.",
     "Chronic feelings of inadequacy can be a sign of deep-seated self-esteem issues. Therapy can help you challenge and change this self-perception."),
    ("I'm struggling to cope with the loss of a beloved pet.",
     "The loss of a pet can be devastating. Therapy can provide a supportive space to process your grief and honor the memory of your furry friend."),
    ("I'm dealing with chronic illness and it's affecting my mental health.",
     "Living with a chronic illness can be emotionally challenging. Therapy can provide coping strategies and support to navigate the emotional ups and downs of chronic illness."),
    ("I feel like I'm constantly on edge and can't relax.",
     "Chronic stress can take a toll on your mental and physical health. Therapy can teach you relaxation techniques and coping strategies to manage stress more effectively."),
    ("I'm struggling with the transition to parenthood.",
     "The transition to parenthood can be overwhelming. Therapy can provide support and guidance as you navigate the joys and challenges of this new phase of life."),
    ("I'm dealing with a toxic work environment and it's affecting my mental health.",
     "Toxic work environments can be incredibly damaging. Therapy can provide support and strategies to cope with workplace stress and navigate your options."),
    ("I feel like I'm stuck in a rut and can't move forward.",
     "Feeling stuck can be frustrating and discouraging. Therapy can help you identify and overcome the barriers holding you back from progress and growth."),
    ("I'm struggling to cope with the death of a loved one.",
     "The death of a loved one can be one of the most challenging experiences in life. Therapy can provide support and guidance as you navigate the grieving process."),
    ("I'm feeling overwhelmed by the demands of caregiving.",
     "Caregiving can be physically and emotionally exhausting. Therapy can provide support and strategies to cope with the challenges of caregiving and prioritize self-care."),
    ("I feel like I'm constantly trying to prove myself to others.",
     "The need to prove oneself can stem from low self-esteem or external pressures. Therapy can help you build self-confidence and recognize your inherent worth."),
    ("I'm struggling to adjust to life after retirement.",
     "Retirement can bring significant life changes and challenges. Therapy can provide support and guidance as you navigate this new phase of life and find meaning and purpose."),
    ("I'm dealing with the aftermath of a natural disaster.",
     "Natural disasters can have profound and long-lasting effects on mental health. Therapy can provide support and coping strategies to navigate the emotional aftermath of a disaster."),
    ("I feel like I'm living someone else's life, not my own.",
     "Feeling disconnected from your own life can be disorienting and distressing. Therapy can help you reconnect with your authentic self and live a more fulfilling life."),
    ("I'm struggling to cope with the impact of a global pandemic.",
     "The COVID-19 pandemic has brought unprecedented challenges and uncertainty. Therapy can provide support and coping strategies to navigate the emotional rollercoaster of living through a pandemic."),
    ("I'm feeling overwhelmed by the news and current events.",
     "Constant exposure to negative news can take a toll on mental health. Therapy can provide support and strategies to manage anxiety and maintain a healthy perspective on current events."),
    ("I'm dealing with the aftermath of a traumatic event.",
     "Trauma can have lasting effects on mental health. Therapy, especially trauma-focused therapy, can provide support and strategies to heal from the effects of trauma."),
    ("I feel like I'm living in a constant state of fear and anxiety.",
     "Living in a constant state of fear and anxiety can be exhausting. Therapy can provide support and coping strategies to manage anxiety and reclaim your life."),
    ("I'm struggling with the loneliness of social isolation.",
     "Social isolation can have significant effects on mental health. Therapy can provide support and strategies to cope with loneliness and maintain social connections, even from a distance."),
    ("I feel like I'm losing my mind and can't trust my own thoughts.",
     "Feeling like you can't trust your own thoughts can be distressing. Therapy can provide support and strategies to manage intrusive thoughts and regain a sense of control."),
    ("I'm dealing with the aftermath of a toxic relationship.",
     "Toxic relationships can leave lasting scars on mental health. Therapy can provide support and strategies to heal from the effects of emotional abuse and regain a sense of self."),
    ("I feel like I'm constantly on the verge of a breakdown.",
     "Living on the verge of a breakdown is unsustainable. Therapy can provide support and strategies to manage stress and prevent burnout."),
    ("I'm struggling with the uncertainty of the future.",
     "Uncertainty about the future can be anxiety-provoking. Therapy can provide support and strategies to manage anxiety and cultivate resilience in the face of uncertainty."),
    ("I feel like I'm drowning in debt and can't see a way out.",
     "Financial stress can have significant effects on mental health. Therapy can provide support and strategies to manage anxiety and develop a plan to address financial challenges."),
    ("I'm struggling to adjust to life with a chronic illness.",
     "Living with a chronic illness can be challenging. Therapy can provide support and strategies to cope with the physical and emotional effects of chronic illness."),
    ("I feel like I'm just going through the motions, without any joy or passion.",
     "Feeling disconnected from joy and passion can be distressing. Therapy can provide support and strategies to reconnect with the things that bring meaning and fulfillment to your life."),
    ("I'm dealing with the loss of a beloved pet and it's affecting me deeply.",
     "The loss of a pet can be devastating. Therapy can provide support and strategies to cope with grief and honor the memory of your furry friend."),
    ("I feel like I'm stuck in a rut and can't see a way out.",
     "Feeling stuck can be frustrating and disheartening. Therapy can provide support and strategies to break out of negative patterns and move forward."),
    ("I'm struggling with chronic pain and it's affecting my mental health.",
     "Living with chronic pain can be exhausting and isolating. Therapy can provide support and strategies to cope with the physical and emotional effects of chronic pain."),
    ("I feel like I'm constantly fighting with my partner and can't communicate effectively.",
     "Relationship conflicts can be distressing and draining. Therapy can provide support and strategies to improve communication and strengthen your relationship."),
    ("I'm dealing with the aftermath of a traumatic event and it's affecting me deeply.",
     "Trauma can have lasting effects on mental health. Therapy can provide support and strategies to heal from the effects of trauma and regain a sense of safety and control."),
    ("I feel like I'm not good enough, no matter how hard I try.",
     "Persistent feelings of inadequacy can be distressing. Therapy can provide support and strategies to challenge negative self-talk and build self-esteem."),
    ("I'm struggling to balance work, family, and personal life.",
     "Finding balance can be challenging in today's fast-paced world. Therapy can provide support and strategies to prioritize self-care and set healthy boundaries."),
    ("I feel like I'm just going through the motions, without any sense of purpose.",
     "Feeling disconnected from purpose can be distressing. Therapy can provide support and strategies to explore your values and passions and find meaning in your life."),
    ("I'm dealing with the emotional aftermath of a divorce.",
     "Divorce can be emotionally challenging. Therapy can provide support and strategies to navigate the grief and loss associated with the end of a marriage."),
    ("I feel like I'm constantly overwhelmed and can't seem to catch a break.",
     "Persistent overwhelm can be exhausting. Therapy can provide support and strategies to manage stress and build resilience."),
    ("I'm struggling to cope with the loss of a loved one and it feels like the pain will never go away.",
     "Grief can feel overwhelming and never-ending. Therapy can provide support and strategies to cope with the pain of loss and find hope for the future."),
    ("I feel like I'm living in a fog and can't seem to snap out of it.",
     "Feeling disconnected from reality can be distressing. Therapy can provide support and strategies to ground yourself and regain clarity."),
    ("I'm dealing with the aftermath of a natural disaster and it's affecting my mental health.",
     "Natural disasters can have profound effects on mental health. Therapy can provide support and strategies to cope with the emotional aftermath and rebuild your life."),
    ("I feel like I'm on the verge of a breakdown and don't know how to stop it.",
     "Living on the verge of a breakdown is unsustainable. Therapy can provide support and strategies to manage stress and prevent burnout."),
    ("I'm struggling to cope with the demands of caregiving and it's taking a toll on my mental health.",
     "Caregiving can be physically and emotionally exhausting. Therapy can provide support and strategies to cope with the challenges and prioritize self-care."),
    ("I feel like I'm drowning in debt and can't see a way out.",
     "Financial stress can have significant effects on mental health. Therapy can provide support and strategies to manage anxiety and develop a plan to address financial challenges."),
    ("I'm struggling to adjust to life with a chronic illness and it's affecting my mental health.",
     "Living with a chronic illness can be challenging. Therapy can provide support and strategies to cope with the physical and emotional effects of chronic illness."),
    ("I feel like I'm just going through the motions, without any joy or passion.",
     "Feeling disconnected from joy and passion can be distressing. Therapy can provide support and strategies to reconnect with the things that bring meaning and fulfillment to your life."),
    ("I'm dealing with the loss of a beloved pet and it's affecting me deeply.",
     "The loss of a pet can be devastating. Therapy can provide support and strategies to cope with grief and honor the memory of your furry friend."),
    ("I feel like I'm stuck in a rut and can't see a way out.",
     "Feeling stuck can be frustrating and disheartening. Therapy can provide support and strategies to break out of negative patterns and move forward."),
    ("I'm struggling with chronic pain and it's affecting my mental health.",
     "Living with chronic pain can be exhausting and isolating. Therapy can provide support and strategies to cope with the physical and emotional effects of chronic pain."),
    ("I feel like I'm constantly fighting with my partner and can't communicate effectively.",
     "Relationship conflicts can be distressing and draining. Therapy can provide support and strategies to improve communication and strengthen your relationship."),
    ("I'm dealing with the aftermath of a traumatic event and it's affecting me deeply.",
     "Trauma can have lasting effects on mental health. Therapy can provide support and strategies to heal from the effects of trauma and regain a sense of safety and control."),
    ("I feel like I'm not good enough, no matter how hard I try.",
     "Persistent feelings of inadequacy can be distressing. Therapy can provide support and strategies to challenge negative self-talk and build self-esteem."),
    ("I'm struggling to balance work, family, and personal life.",
     "Finding balance can be challenging in today's fast-paced world. Therapy can provide support and strategies to prioritize self-care and set healthy boundaries."),
    ("I feel like I'm just going through the motions, without any sense of purpose.",
     "Feeling disconnected from purpose can be distressing. Therapy can provide support and strategies to explore your values and passions and find meaning in your life."),
    ("I'm dealing with the emotional aftermath of a divorce.",
     "Divorce can be emotionally challenging. Therapy can provide support and strategies to navigate the grief and loss associated with the end of a marriage."),
    ("I feel like I'm constantly overwhelmed and can't seem to catch a break.",
     "Persistent overwhelm can be exhausting. Therapy can provide support and strategies to manage stress and build resilience."),
    ("I'm struggling to cope with the loss of a loved one and it feels like the pain will never go away.",
     "Grief can feel overwhelming and never-ending. Therapy can provide support and strategies to cope with the pain of loss and find hope for the future."),
    ("I feel like I'm living in a fog and can't seem to snap out of it.",
     "Feeling disconnected from reality can be distressing. Therapy can provide support and strategies to ground yourself and regain clarity."),
    ("I'm dealing with the aftermath of a natural disaster and it's affecting my mental health.",
     "Natural disasters can have profound effects on mental health. Therapy can provide support and strategies to cope with the emotional aftermath and rebuild your life."),
    ("I feel like I'm on the verge of a breakdown and don't know how to stop it.",
     "Living on the verge of a breakdown is unsustainable. Therapy can provide support and strategies to manage stress and prevent burnout."),
    ("I'm struggling to cope with the demands of caregiving and it's taking a toll on my mental health.",
     "Caregiving can be physically and emotionally exhausting. Therapy can provide support and strategies to cope with the challenges and prioritize self-care.")]


patterns= data


# In[5]:


import nltk
import random

def preprocess_data(data):
    processed_data = []
    for question, answer in data:
        tokens = set(nltk.word_tokenize(question.lower()))
        processed_data.append((tokens, question, answer))
    return processed_data

def find_best_match(user_input, data):
    user_tokens = set(nltk.word_tokenize(user_input.lower()))
    best_match = None
    highest_similarity = 0
    
    for tokens, question, answer in data:
        similarity_score = len(user_tokens.intersection(tokens))
        if similarity_score > highest_similarity:
            highest_similarity = similarity_score
            best_match = (question, answer)
    
    return best_match
def get_reply(user_input, data):
    best_match = find_best_match(user_input, data)
    
    if best_match is None:
        return "I'm sorry, I don't understand. Can you please rephrase or provide more information?"
    return best_match[1]
processed_patterns = preprocess_data(patterns)




# In[6]:


import tkinter as tk
from tkinter import scrolledtext

def handle_input(event=None):
    user_input = user_entry.get()
    chat_area.config(state='normal')
    chat_area.insert(tk.END, f"You: {user_input}\n")
    response = get_reply(user_input, processed_patterns) 
    chat_area.insert(tk.END, f"HappyChat: {response}\n")
    chat_area.config(state='disabled')
    user_entry.delete(0, tk.END)
    if user_input.lower() == 'bye':
        root.destroy()


def clear_default_text(event):
    default_text = "Type your message here"
    if user_entry.get() == default_text:
        user_entry.delete(0, tk.END)


root = tk.Tk()
root.title("HappyChat")

background_color = "#6495ED"  
root.configure(bg=background_color)


chat_frame = tk.Frame(root, bg="#e6e6e6")
chat_frame.place(relwidth=0.75, relheight=0.8, relx=0.1, rely=0.1)


chat_area = scrolledtext.ScrolledText(chat_frame, wrap=tk.WORD, bg="#ffffff", fg="#000000", state='disabled')
chat_area.pack(padx=10, pady=10, fill=tk.BOTH, expand=True)
chat_area.config(state='normal')
chat_area.insert(tk.END, "HappyChat: Welcome to HappyChat! I am a mental health Chatbot. Is there anything you would like to share with me?\n")
chat_area.config(state='disabled')

default_text = "Type your message here"
user_entry = tk.Entry(root, bg="#d3d3d3", fg="#000000", font=("Arial", 12))
user_entry.place(relwidth=0.6, relheight=0.05, relx=0.1, rely=0.9)
user_entry.insert(0, default_text)  # Insert default text
user_entry.bind("<Key>", clear_default_text)  # Bind event to clear default text
user_entry.bind("<Return>", handle_input)


send_button = tk.Button(root, text="Send", bg="#4CAF50", fg="#ffffff", command=handle_input)
send_button.place(relwidth=0.15, relheight=0.05, relx=0.72, rely=0.9)

watermark_label = tk.Label(root, text="Your Path to Wellness Starts with a HappyChat", bg=background_color, fg="#ffffff", font=("Arial", 20, "italic"))
watermark_label.place(relx=0.5, rely=0.5, anchor=tk.CENTER)

root.mainloop()


# In[ ]:




